services:
  app:
    container_name: app
    build: ./app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
      - ./static:/app/static
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: always
    image: nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./images:/images
      - ./logs:/var/log/nginx
      - ./static:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - frontend-network

  db:
    container_name: db
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - image_hosting_data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: always

volumes:
  image_hosting_data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge